### ISSUE TITLE
ChessPosition Ordinal 

### ISSUE THREAD

**Issue by Samiimasmoudii** [Badis8/chessSimulator#1]
Hey Bedis, Great work I wanted to suggest something. 

The use of ordinal() to determine board positions assumes that the ChessPosition enum is strictly ordered and directly maps to board indices (0 to 63). While this works under current assumptions, it introduces potential fragility.

If ChessPosition is reordered or additional values are introduced, the logic will break silently.
ordinal() exposes internal enum indexing, which may not align with board semantics.

Suggested Change:
Refactor ChessPosition to provide explicit methods for positional data, such as row and column indices or board coordinates. For example, add methods like getRow() and getColumn() in the ChessPosition enum to encapsulate these calculations.

**Comment by Badis8** [comment]
hello samy , 

about the ordinal method i didn't wrap it up into getters  on the pretext that a chess board is and will alwyas be a 8 by 8 grid. 
i implmented the enum to show case the domain on the coding style. (writing piece.move(A8) instead of directly indexing) 
but seeing that the domain isnt that complex ,  and the domaine mapping makes the code running a bit slower i just eliminated the enum entirely and opted to have a normal matrix of pieces wrapped up in the board, when a player (for me a player is a bot) wants to know the disposition of the board he has to use board methods.
